### ISSUE TITLE
The plugin does not throw a bug when ref is used with styled components.

### ISSUE THREAD

**Issue by leonschwanitz** [danbovey/react-infinite-scroller#202]
Apparently React Infinity Scrollbar doesn't check if the ref is really valid. Because if you use styled components you should use innerRef. I think with a simple if statement you would save others a lot of time. :)

* Styled Components: https://www.styled-components.com/

**Comment by JackHull** [comment]
Explanation: This results in react-infinite-scroller not being able to mount the scroll event to the parent node, as styled-components does not passthrough event-handling to the actual DOM (inner-)ref, when using just ref - our proposal to this problem is simply checking, if the provided ref actually provides a handleable scroll listener.
